### ISSUE TITLE
Bayesian optimization

### ISSUE THREAD

**Issue by yangxiufengsia** [HIPS/molecule-autoencoder#5]
Can you share the code of bayesian optimization used in this paper?

**Comment by duvenaud** [comment]
@jmhernandezlobato wrote and ran that code.  Miguel, do you feel like sharing it?

**Comment by jmhernandezlobato** [comment]
I am planing to make the code public. I will try to upload it by next week, if possible.

**Comment by spadavec** [comment]
@jmhernandezlobato was your BO code ever released where I can look at it? Much appreciated!
